import { Course, Review, Branch } from './types';

export const branches: Branch[] = [
  { id: 'cse', name: 'Computer Science & Engineering', code: 'CSE' },
  { id: 'ece', name: 'Electronics & Communication Engineering', code: 'ECE' },
  { id: 'mech', name: 'Mechanical Engineering', code: 'MECH' },
  { id: 'civil', name: 'Civil Engineering', code: 'CIVIL' },
  { id: 'eee', name: 'Electrical & Electronics Engineering', code: 'EEE' },
  { id: 'it', name: 'Information Technology', code: 'IT' },
];

export const courses: Course[] = [
  {
    id: '1',
    name: 'Data Structures and Algorithms',
    code: 'CSE201',
    description: 'Fundamental concepts of data structures including arrays, linked lists, stacks, queues, trees, and graphs. Algorithm analysis and design techniques.',
    professor: 'Dr. Sarah Johnson',
    branch: 'cse',
    semester: 3,
    credits: 4,
    type: 'core',
    averageRating: 4.5,
    difficulty: 'moderate',
    totalReviews: 127,
    facilities: 4.2,
    teaching: 4.7,
  },
  {
    id: '2',
    name: 'Database Management Systems',
    code: 'CSE301',
    description: 'Introduction to database concepts, relational model, SQL, normalization, transaction processing, and database design.',
    professor: 'Prof. Michael Chen',
    branch: 'cse',
    semester: 5,
    credits: 3,
    type: 'core',
    averageRating: 4.2,
    difficulty: 'moderate',
    totalReviews: 98,
    facilities: 4.0,
    teaching: 4.3,
  },
  {
    id: '3',
    name: 'Machine Learning',
    code: 'CSE401',
    description: 'Introduction to machine learning algorithms, supervised and unsupervised learning, neural networks, and practical applications.',
    professor: 'Dr. Emily Rodriguez',
    branch: 'cse',
    semester: 7,
    credits: 4,
    type: 'elective',
    averageRating: 4.8,
    difficulty: 'hard',
    totalReviews: 156,
    facilities: 4.6,
    teaching: 4.9,
  },
  {
    id: '4',
    name: 'Web Development',
    code: 'CSE302',
    description: 'Full-stack web development including HTML, CSS, JavaScript, React, Node.js, and database integration.',
    professor: 'Mr. David Kumar',
    branch: 'cse',
    semester: 6,
    credits: 3,
    type: 'elective',
    averageRating: 4.6,
    difficulty: 'moderate',
    totalReviews: 143,
    facilities: 4.4,
    teaching: 4.5,
  },
  {
    id: '5',
    name: 'Digital Signal Processing',
    code: 'ECE301',
    description: 'Discrete-time signals and systems, Z-transform, digital filter design, and implementation using MATLAB.',
    professor: 'Dr. Priya Sharma',
    branch: 'ece',
    semester: 5,
    credits: 4,
    type: 'core',
    averageRating: 3.9,
    difficulty: 'hard',
    totalReviews: 89,
    facilities: 3.8,
    teaching: 4.1,
  },
  {
    id: '6',
    name: 'VLSI Design',
    code: 'ECE401',
    description: 'Very Large Scale Integration design, CMOS technology, logic design, and chip architecture.',
    professor: 'Prof. Rajesh Gupta',
    branch: 'ece',
    semester: 7,
    credits: 4,
    type: 'elective',
    averageRating: 4.3,
    difficulty: 'hard',
    totalReviews: 67,
    facilities: 4.1,
    teaching: 4.4,
  },
  {
    id: '7',
    name: 'Thermodynamics',
    code: 'MECH201',
    description: 'Laws of thermodynamics, thermodynamic processes, heat engines, refrigeration cycles.',
    professor: 'Dr. Arun Patel',
    branch: 'mech',
    semester: 3,
    credits: 3,
    type: 'core',
    averageRating: 4.1,
    difficulty: 'moderate',
    totalReviews: 112,
    facilities: 3.9,
    teaching: 4.2,
  },
  {
    id: '8',
    name: 'Fluid Mechanics',
    code: 'MECH301',
    description: 'Properties of fluids, fluid statics, fluid dynamics, flow measurements, and applications.',
    professor: 'Prof. Sunita Verma',
    branch: 'mech',
    semester: 5,
    credits: 4,
    type: 'core',
    averageRating: 3.8,
    difficulty: 'hard',
    totalReviews: 95,
    facilities: 3.7,
    teaching: 3.9,
  },
  {
    id: '9',
    name: 'Structural Analysis',
    code: 'CIVIL301',
    description: 'Analysis of statically determinate and indeterminate structures, influence lines, and deflections.',
    professor: 'Dr. Ravi Krishnan',
    branch: 'civil',
    semester: 5,
    credits: 4,
    type: 'core',
    averageRating: 4.0,
    difficulty: 'moderate',
    totalReviews: 78,
    facilities: 3.8,
    teaching: 4.1,
  },
  {
    id: '10',
    name: 'Power Systems',
    code: 'EEE301',
    description: 'Power generation, transmission, distribution, load flow studies, and stability analysis.',
    professor: 'Prof. Meera Joshi',
    branch: 'eee',
    semester: 5,
    credits: 4,
    type: 'core',
    averageRating: 4.2,
    difficulty: 'moderate',
    totalReviews: 87,
    facilities: 4.0,
    teaching: 4.3,
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    courseId: '1',
    studentName: 'Alex Kumar',
    isAnonymous: false,
    overallRating: 5,
    difficultyRating: 3,
    facilitiesRating: 4,
    teachingRating: 5,
    feedback: 'Excellent course! Dr. Johnson explains concepts very clearly and the lab sessions are well-structured.',
    date: '2024-01-15',
    helpful: 23,
  },
  {
    id: '2',
    courseId: '1',
    isAnonymous: true,
    overallRating: 4,
    difficultyRating: 4,
    facilitiesRating: 4,
    teachingRating: 4,
    feedback: 'Good content but requires a lot of practice. The assignments are challenging but fair.',
    date: '2024-01-10',
    helpful: 18,
  },
  {
    id: '3',
    courseId: '3',
    studentName: 'Priya Singh',
    isAnonymous: false,
    overallRating: 5,
    difficultyRating: 5,
    facilitiesRating: 5,
    teachingRating: 5,
    feedback: 'Amazing course! Dr. Rodriguez is brilliant and the practical projects are industry-relevant.',
    date: '2024-01-20',
    helpful: 45,
  },
  {
    id: '4',
    courseId: '4',
    isAnonymous: true,
    overallRating: 4,
    difficultyRating: 3,
    facilitiesRating: 4,
    teachingRating: 4,
    feedback: 'Very practical course. Learned modern web technologies that are directly applicable in internships.',
    date: '2024-01-12',
    helpful: 31,
  },
  {
    id: '5',
    courseId: '5',
    studentName: 'Arjun Reddy',
    isAnonymous: false,
    overallRating: 3,
    difficultyRating: 5,
    facilitiesRating: 3,
    teachingRating: 4,
    feedback: 'Challenging course with heavy mathematical content. Good for those interested in signal processing.',
    date: '2024-01-08',
    helpful: 12,
  },
];

export const featuredCourses = courses.filter(course => course.averageRating >= 4.5);
